### ISSUE TITLE
Unable to integrate paypal SDK using pod file

### ISSUE THREAD

**Issue by SatyanarayanaKV** [CocoaPods/Rainforest#48]
[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

Above is terminal message 

 The SDK has integrated to my build but when we import class file and run the build it throws an errors.

Please help me.

**Comment by segiddins** [comment]
This is not the appropriate repo to open up an issue with CocoaPods on. In addition, since this is a usage question, a more appropriate forum to ask it on would be a place like StackOverflow.
