### ISSUE TITLE
`rake bootstrap` fails with ruby version error

### ISSUE THREAD

**Issue by JakeSc** [CocoaPods/Rainforest#72]
I read on https://blog.cocoapods.org/starting-open-source that
> It should be as simple as possible to get started, that means setup of environment and finding issue which are suited for contributors who are not yet familiar with the code base. CocoaPods does both of these very well.

However, running Rainforest -> `rake bootstrap` leaves me with this error:
```
Installing gems
--------------------------------------------------------------------------------

bundle install
Fetching gem metadata from http://rubygems.org/...........
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
cocoapods-docs-0.2.0 requires ruby version = 2.0, which is incompatible with the current version, ruby 2.3.0p0
rake aborted!
Command failed with status (5): [bundle install...]
```

```
$ rvm list

rvm rubies

   ruby-1.9.3-p551 [ x86_64 ]
   ruby-2.0.0-p648 [ x86_64 ]
   ruby-2.1.0 [ x86_64 ]
=* ruby-2.3.0 [ x86_64 ]
```

When switching to Ruby 2.0.0 and running `rake bootstrap`, I see:
```
$ rake bootstrap
rake aborted!
undefined method `scope' for #<Rake::NameSpace:0x007fb813814c00>
Rainforest/Rakefile:1133:in `block (2 levels) in <top (required)>'
Rainforest/Rakefile:1122:in `block in <top (required)>'
Rainforest/Rakefile:1106:in `<top (required)>'
```

How can I work around this to run a development version of `pod` so I can help debug issues?

Thanks!

**Comment by 0oneo** [comment]
@JakeSc you `gem install rake` to pass `undefined method 'scope' ` error, but another error will happen:

```ruby
bundle install
YAML safe loading is not available. Please upgrade psych to a version that supports safe loading (>= 2.0).
Fetching gem metadata from https://gems.ruby-china.org/..........
rubocop-0.51.0 requires ruby version >= 2.1.0, which is incompatible with the current version, ruby 2.0.0p648
```

so, cocoapods-doc require ruby equals to 2.0, but rubocop-0.51.0 require ruby >= 2.1.0

**Comment by segiddins** [comment]
We just need to fix the requirement in `cocoapods-doc`
